const dummyData = [
  {
    id: 1,
    instructor_name: "Ken",
    type: "Yoga",
    date: "Aug 1",
    time: "11:00",
    duration: "1 hour",
    intensity: "Beginner",
    location: "Central Park",
    capacity: 25,
    registered: 0,
  },
  {
    id: 2,
    instructor_name: "Bob",
    type: "Kickboxing",
    date: "Aug 2",
    time: "12:30",
    duration: "1 hour",
    intensity: "Intermediate",
    location: "YMCA",
    capacity: 15,
    registered: 0,
  },
  {
    id: 3,
    instructor_name: "Carl",
    type: "Weightlifting",
    date: "Aug 7",
    time: "2:00",
    duration: "2 hour",
    intensity: "Advanced",
    location: "YMCA",
    capacity: 10,
    registered: 0,
  },
  {
    id: 4,
    instructor_name: "Kasey",
    type: "Biking",
    date: "Aug 6",
    time: "8:00",
    duration: "4 hour",
    intensity: "Intermediate",
    location: "Greenway Trail",
    capacity: 12,
    registered: 0,
  },
  {
    id: 2,
    instructor_name: "Michelle",
    type: "Swimming",
    date: "Aug 4",
    time: "5:00",
    duration: "1.5 hour",
    intensity: "Beginner",
    location: "Town Pool",
    capacity: 5,
    registered: 0,
  },
];

export default dummyData;
